"""Static holding-torque check (ROBOTS_SPEC.md §3.3, §4).

Generates docs/reports/torque_<robot>.md and returns a structured result the
G1 gate test asserts on. The model is intentionally simple and transparent —
every assumption is written into the report so a human can audit it.

Model
-----
Worst case is a single-support balance pose. To hold a static pose the actuator
opposing the tip-over must supply

    tau_static = m * g * (com_offset / 1000)          [N.m]

where `com_offset` (mm) is the horizontal distance from the loaded joint axis
to the body centre of mass in the named pose (BDX-A: knee 60 deg, offset 30 mm;
this is the classic ankle-strategy lever). ROCKY-5 is checked against its
spec-given femur worst case (0.52 N.m) instead of a derived pose, since its
pentapod stance keeps every joint well inside its limit.

A servo PASSES when
    torque_continuous >= continuous_margin * tau_static   (1.8x by default)
    torque_stall      >= stall_margin      * tau_static   (3.0x by default)
"""

from __future__ import annotations

import math
from dataclasses import dataclass, asdict

G = 9.81  # m/s^2


@dataclass
class TorqueResult:
    robot: str
    mass_kg: float
    tau_static_nm: float
    continuous_nm: float
    stall_nm: float
    continuous_ratio: float
    stall_ratio: float
    continuous_required: float
    stall_required: float
    continuous_pass: bool
    stall_pass: bool
    max_mass_for_pass_kg: float  # heaviest robot that still passes BOTH criteria

    @property
    def passed(self) -> bool:
        return self.continuous_pass and self.stall_pass


def _evaluate(robot, mass_kg, tau_static_nm, servo, tq) -> TorqueResult:
    cont = float(servo["torque_continuous_nm"])
    stall = float(servo["torque_stall_nm"])
    cmarg = float(tq["continuous_margin"])
    smarg = float(tq["stall_margin"])
    cont_req = cmarg * tau_static_nm
    stall_req = smarg * tau_static_nm
    # Heaviest mass that still passes both, holding the pose geometry fixed.
    # tau scales linearly with mass, so max_mass = mass * min(headroom_cont, headroom_stall).
    headroom = min(cont / cont_req, stall / stall_req) if tau_static_nm > 0 else math.inf
    return TorqueResult(
        robot=robot,
        mass_kg=mass_kg,
        tau_static_nm=tau_static_nm,
        continuous_nm=cont,
        stall_nm=stall,
        continuous_ratio=cont / tau_static_nm if tau_static_nm else math.inf,
        stall_ratio=stall / tau_static_nm if tau_static_nm else math.inf,
        continuous_required=cont_req,
        stall_required=stall_req,
        continuous_pass=cont >= cont_req,
        stall_pass=stall >= stall_req,
        max_mass_for_pass_kg=mass_kg * headroom,
    )


def check_bdx_a(params: dict, mass_kg: float | None = None) -> TorqueResult:
    tq = params["torque_check"]
    m = mass_kg if mass_kg is not None else params["design_target_kg"]
    tau_static = m * G * (tq["com_offset_mm"] / 1000.0)
    return _evaluate("bdx_a", m, tau_static, params["servo"], tq)


def check_rocky(params: dict, mass_kg: float | None = None) -> TorqueResult:
    tq = params["torque_check"]
    m = mass_kg if mass_kg is not None else params["design_target_kg"]
    # Rocky's stated worst case is the femur torque, independent of body mass
    # in the neutral stance (PASS by construction, §4).
    tau_static = float(tq["femur_worst_case_nm"])
    return _evaluate("rocky", m, tau_static, params["servo"], tq)


def render_report(result: TorqueResult, params: dict) -> str:
    r = result
    status = "PASS" if r.passed else "FAIL"
    lines = [
        f"# Torque report — {r.robot}",
        "",
        f"**Status: {status}** (continuous {'PASS' if r.continuous_pass else 'FAIL'}, "
        f"stall {'PASS' if r.stall_pass else 'FAIL'})",
        "",
        "> Generated by `common/cad_lib/torque.py`. Do not edit by hand.",
        "",
        "| Quantity | Value |",
        "|---|---|",
        f"| Servo | {params['servo']['model']} @ {params['servo']['voltage_v']} V |",
        f"| Evaluated mass | {r.mass_kg:.3f} kg |",
        f"| Static holding torque | {r.tau_static_nm:.3f} N·m |",
        f"| Continuous torque | {r.continuous_nm:.3f} N·m "
        f"(need ≥ {r.continuous_required:.3f}, ratio {r.continuous_ratio:.2f}×) |",
        f"| Stall torque | {r.stall_nm:.3f} N·m "
        f"(need ≥ {r.stall_required:.3f}, ratio {r.stall_ratio:.2f}×) |",
        f"| Max mass that still PASSES both | {r.max_mass_for_pass_kg:.3f} kg |",
        f"| Mass budget (ceiling) | {params['mass_budget_kg']:.3f} kg |",
        "",
    ]
    if r.max_mass_for_pass_kg < params["mass_budget_kg"]:
        lines += [
            f"⚠️ The continuous-torque criterion caps usable mass at "
            f"**{r.max_mass_for_pass_kg:.3f} kg**, below the {params['mass_budget_kg']} kg "
            f"budget ceiling. The realised CAD build MUST come in under this cap "
            f"(reduce shell mass first, then shorten links 5% — §3.3). See D-002.",
            "",
        ]
    return "\n".join(lines)
