#!/usr/bin/env python3
"""Generate docs/reports/integration.md — the physical-integration + shared-BOM
report. Answers "is everything accounted for?" (wiring, cooling, sensors, power,
compute, charging) and "what's reused across both robots?" (D-010 reuse goal).

Reads common/cad_lib/components.py (single source of truth). Idempotent.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from common.cad_lib.components import components_for, charging_base_components  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reports" / "integration.md"


def _by_component(robot):
    """name -> (component, total_qty)."""
    agg = {}
    for pl in components_for(robot):
        c = pl.component
        if c.name in agg:
            agg[c.name] = (c, agg[c.name][1] + pl.qty)
        else:
            agg[c.name] = (c, pl.qty)
    return agg


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    robots = ("bdx_a", "rocky")
    aggs = {r: _by_component(r) for r in robots}

    lines = ["# PROJECT DUET — Integration & shared BOM", "",
             "> Generated by scripts/gen_integration_report.py from components.py.", ""]

    # Shared components (present in BOTH robots) — the reuse (D-010).
    shared = sorted(set(aggs["bdx_a"]) & set(aggs["rocky"]))
    lines += ["## Shared across BOTH robots (reuse — D-010)", "",
              "| component | category | each (g) | bdx_a | rocky |",
              "|---|---|---|---|---|"]
    for name in shared:
        c = aggs["bdx_a"][name][0]
        lines.append(f"| {name} | {c.category} | {c.mass_g:.0f} | "
                     f"{aggs['bdx_a'][name][1]} | {aggs['rocky'][name][1]} |")
    lines.append("")

    # Per-robot full component list + provisions (nothing forgotten).
    for r in robots:
        total = sum(c.mass_g * q for c, q in aggs[r].values())
        lines += [f"## {r} — {len(aggs[r])} component types, {total/1000:.2f} kg", "",
                  "| component | qty | dims (mm) | mass (g) | provision | routing |",
                  "|---|---|---|---|---|---|"]
        by_cat = defaultdict(list)
        for c, q in aggs[r].values():
            by_cat[c.category].append((c, q))
        for cat in sorted(by_cat):
            for c, q in sorted(by_cat[cat], key=lambda x: -x[0].mass_g * x[1]):
                dims = "x".join(f"{d:.0f}" for d in c.dims_mm)
                conn = ",".join(c.connectors) or "-"
                lines.append(f"| {c.name} | {q} | {dims} | {c.mass_g:.0f} | {c.provision} | {conn} |")
        lines.append("")

    # Charging dock.
    tx = charging_base_components()[0].component
    lines += ["## Charging dock (shared)", "",
              f"- {tx.name}: {tx.mass_g:.0f} g, provision {tx.provision} "
              f"— Qi transmitter both robots park on.", ""]

    OUT.write_text("\n".join(lines))
    print(f"[integration-report] wrote {OUT.relative_to(ROOT)} "
          f"({len(shared)} shared component types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
