#!/usr/bin/env python3
"""CAD generation driver — the `_cad` stage / gate-2 producer (§4.5, §8).

For one robot: generate every registered part, export a decimated STL, run mesh
QA, and accumulate mass properties. Writes:
  * <robot>/cad/parts/*.stl        exported geometry
  * docs/bom/<robot>.csv           printed parts + inserts (COTS link left blank)
  * docs/reports/mass_<robot>.md   per-part + total mass (feeds torque re-check)

Runs under scripts/cadpy (build123d present). Exits non-zero if any part fails
QA so the gate fails here, never at the slicer.

Usage: cadpy scripts/gen_cad.py <robot>
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import trimesh  # noqa: E402

from common.cad_lib.registry import parts_for  # noqa: E402
from common.cad_lib.export import export_part_stl, part_mass  # noqa: E402
from common.export.qa import check_mesh  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent


def generate(robot: str) -> int:
    parts_dir = ROOT / robot / "cad" / "parts"
    bom_dir = ROOT / "docs" / "bom"
    reports = ROOT / "docs" / "reports"
    for d in (parts_dir, bom_dir, reports):
        d.mkdir(parents=True, exist_ok=True)

    rows, mass_rows, total_g = [], [], 0.0
    failures = []
    for mod in parts_for(robot):
        meta = mod.META
        p = mod.part()
        stl = export_part_stl(p, parts_dir / f"{meta.name}.stl")
        mesh = trimesh.load(stl)
        qa = check_mesh(mesh, meta.name, meta.min_wall_mm)
        mp = part_mass(p, meta)
        total_g += mp.total_mass_g
        status = "PASS" if qa.passed else "FAIL"
        print(f"[gen_cad:{robot}] {meta.name:14} {status} "
              f"tris={len(mesh.faces):5d} mass={mp.unit_mass_g:6.1f} g x{meta.qty} "
              f"min_wall={qa.min_wall_mm}")
        if not qa.passed:
            failures.append((meta.name, qa.failures))
        rows.append((meta.name, meta.material, meta.qty, meta.plate_group,
                     ";".join(f"{i.kind}x{i.count}" for i in meta.inserts)))
        mass_rows.append((meta.name, meta.material, meta.qty,
                          f"{mp.unit_mass_g:.1f}", f"{mp.total_mass_g:.1f}"))

    # BOM
    with (bom_dir / f"{robot}.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["part", "material", "qty", "plate_group", "inserts", "unit_cost", "link"])
        for name, mat, qty, plate, inserts in rows:
            w.writerow([name, mat, qty, plate, inserts, "", ""])

    # Mass report
    lines = [f"# Mass properties — {robot}", "",
             "> Generated by scripts/gen_cad.py. Do not edit by hand.", "",
             "| part | material | qty | unit (g) | total (g) |",
             "|---|---|---|---|---|"]
    lines += [f"| {n} | {m} | {q} | {u} | {t} |" for n, m, q, u, t in mass_rows]
    lines += ["", f"**Total (registered parts): {total_g:.1f} g "
              f"({total_g/1000:.3f} kg)**",
              "", "_Partial — only seed parts are registered so far; not yet the "
              "full robot mass. The G1 torque re-check uses this once the part set "
              "is complete._"]
    (reports / f"mass_{robot}.md").write_text("\n".join(lines))

    if failures:
        print(f"[gen_cad:{robot}] QA FAILURES: {failures}")
        return 1
    return 0


def main() -> int:
    robots = sys.argv[1:] or ["bdx_a", "rocky"]
    rc = 0
    for r in robots:
        rc |= generate(r)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
