#!/usr/bin/env python3
"""Generate docs/reports/WEEKEND_REPORT.md — the weekend Definition-of-Done (§DoD/G9).

Pulls together, per track: gate status, training results (final metrics + best
checkpoint from the rsl_rl runs), CAD/print artifacts, all D-### decisions, and a
ranked "human next actions" list. Idempotent; safe to re-run any time.
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / "docs" / "reports"


def _final_metrics(exp_glob: str) -> dict | None:
    from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
    runs = sorted(glob.glob(str(ROOT / "runs" / "rsl_rl" / exp_glob / "*" / "events.*")))
    if not runs:
        return None
    ea = EventAccumulator(runs[-1]); ea.Reload()
    k = ea.Tags()["scalars"]
    def g(t):
        return ea.Scalars(t)[-1].value if t in k else None
    run_dir = Path(runs[-1]).parent
    ckpts = sorted(glob.glob(str(run_dir / "model_*.pt")),
                   key=lambda p: int(re.search(r"model_(\d+)", p).group(1)))
    return {
        "iters": len(ea.Scalars("Train/mean_reward")) if "Train/mean_reward" in k else 0,
        "reward": g("Train/mean_reward"),
        "vel_err_xy": g("Metrics/base_velocity/error_vel_xy"),
        "fall_rate": g("Episode_Termination/base_contact"),
        "checkpoint": str(Path(ckpts[-1]).relative_to(ROOT)) if ckpts else "—",
    }


def _decisions() -> list[str]:
    text = (ROOT / "docs" / "DECISIONS.md").read_text()
    return re.findall(r"\*\*(D-\d+[^*]*)\*\*", text)


def _fmt(m: dict | None) -> str:
    if not m:
        return "not run yet"
    return (f"{m['iters']} iters · reward {m['reward']:+.1f} · "
            f"vel-err {m['vel_err_xy']:.3f} · fall {m['fall_rate']:.3f}\n  "
            f"best checkpoint: `{m['checkpoint']}`")


def main() -> int:
    REPORTS.mkdir(parents=True, exist_ok=True)
    bdx = _final_metrics("bdxr_rough")
    rocky = _final_metrics("rocky_flat")
    lines = [
        "# PROJECT DUET — Weekend Report",
        "",
        "> Generated by `scripts/gen_weekend_report.py`. Reproducible; do not hand-edit.",
        "",
        "## BDX-A (BDX-R, exact — D-007)",
        f"- Training (`Bdxr-Velocity-Flat-v0`): {_fmt(bdx)}",
        "- Model: vendored BDX-R (14 DOF, full-scale, Robstride). Gates: G0✅ (Isaac smoke).",
        "- Improvements: Qi-15W belly RX mount (CAD, QA✅); balancing via more training.",
        "",
        "## ROCKY-5 (our design)",
        f"- Training (`Duet-Rocky-Flat-v0`): {_fmt(rocky)}",
        "- Model: 17 DOF (15 legs + 2 front grips, D-008). Gates: G1✅ G2✅ G3✅.",
        "- CAD: core plate, rock carapace (§4/D-009), belly RX plate, charging dock,"
        " 3-finger hands — all QA✅.",
        "",
        "## Decisions",
    ]
    lines += [f"- {d.strip()}" for d in _decisions()]
    lines += [
        "",
        "## Ranked human next actions",
        "1. Review the two walking policies (TensorBoard :6006 + eval clips).",
        "2. BDX-A: order Robstride actuators + Jetson Orin Nano per BDX-R BOM.",
        "3. Reward-tune both for tighter velocity tracking (current vel-err ~0.15).",
        "4. ROCKY-5: split carapace into 2 pieces + dovetails; print coupons first.",
        "5. Source Qi-15W modules (RX + dock TX) for wireless charging.",
    ]
    out = REPORTS / "WEEKEND_REPORT.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"[weekend-report] wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
